spring:
   profiles:
      active: dev
---
# common spring boot configuration
spring:

   # devtools - live reload
   livereload:
      enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
---
# dev profile spring boot configuration
spring:
   config:
      activate:
         on-profile: dev

   # datasource
   # password 암호화 필요
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url : jdbc:mysql://192.168.0.63:3307/webdb?characterEncoding=UTF-8&serverTimezone=UTC
      username: webdb
      password: webdb
      # initialSize, maxActive
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
---
# production profile spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   # datasource
   # password 암호화 필요
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url : jdbc:mysql://211.14.5.6:3307/webdb?characterEncoding=UTF-8&serverTimezone=UTC
      username: webdb
      password: abcdefg
      # initialSize, maxActive
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
---
# server
server:

   # server
   port: 8080
   servlet:
      context-path: /mysite06

      # http
      encoding:
         charset: utf-8
         enabled: true
         forced:
            request: false
            response: false
---
# mybatis
mybatis:
   config-loation: classpath:mybatis/configuration.xml
---
# logging


